server:
  port: 11142
  tomcat:
    max-threads: 800
    uri-encoding: UTF-8
spring:
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  application:
    name: aq-zuul
eureka:
  client:
    service-url:
      defaultZone: http://aq-security:aq-security@10.138.20.90:8761/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ipAddress}:${spring.application.instance_id:${server.port}}
    metadata-map:
      zone: ABC      # eureka可以理解的元数据
      lilizhou: BBC  # 不会影响客户端行为
    lease-renewal-interval-in-seconds: 5
logging:
  file: aq-zuul.log
zuul:
  ignored-services: "*"
  prefix: /api
  routes:
    school:
      path: /school/**
      serviceId: aq-school

    shop:
      path: /shop/**
      serviceId: aq-shop